name: JellyfishModel_GPU
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.12.3
  - pytorch::pytorch=2.5.1
  - pytorch::torchvision=0.20.1
  - pytorch::pytorch-cuda=11.8  # or 12.1 depending on your system
  - numpy=2.3.3
  - matplotlib=3.9.1
  - pillow=10.3.0
  - scikit-learn=1.7.2
  - scipy=1.16.2
  - pyyaml=6.0.3
  - tqdm
  - pip
  - pip:
    - wandb==0.22.1
    - gitpython==3.1.45
    - pydantic==2.11.9
    - protobuf==6.32.1
    - sentry-sdk==2.39.0
    - click==8.3.0
